AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys IAM roles and policies required for the AWS EKS Quick Start (qs-1p7nknohl)
Parameters:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Bastion security group ID
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC.
    Type: String
Resources:
  BastionSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'BastionSecurityGroup'
      IpProtocol: tcp
      FromPort: 8081
      ToPort: 16686
      CidrIp: !Ref 'VPCCIDR'