AWSTemplateFormatVersion: "2010-09-09"
Description: Create FileNet Content Manager repos in ECR, download container images from IBM Production Entitlement Registry, and push to AWS ECR
Parameters:
  BastionASGName:
    Description: Auto Scaling Group Name of the Bastion Host
    Type: String
  DockerRegistryEntitlementKey:
    Description: Paste the Entitlement Key here for Quick Start to pull docker images
    Type: String
  CPERepoName:
    Type: String
    Description: Randomly generated CPE docker repo name from ECR
  ICNRepoName:
    Type: String
    Description: Randomly generated ICN docker repo name from ECR
  CSSRepoName:
    Type: String
    Description: Randomly generated CSS docker repo name from ECR
  CRSRepoName:
    Type: String
    Description: Randomly generated CRS docker repo name from ECR
  CMISRepoName:
    Type: String
    Description: Randomly generated CMIS docker repo name from ECR
  CPETag:
    Type: String
    Description: CPE Container tag
  ICNTag:
    Type: String
    Description: ICN Container tag
  CSSTag:
    Type: String
    Description: CSS Container tag
  CRSTag:
    Type: String
    Description: GraphQL Container tag
  CMISTag:
    Type: String
    Description: CMIS Container tag
  ECRRegion:
    Description: Region where ECR is located
    Type: String
  ECROrg:
    Description: The AWS organization where ECR is located
    Type: String
  FinalLogin:
    Type: String
    Description: Final Login string
  FNCMSSMSendCommandLambdaRoleARN:
    Type: String
    Description: ARN of the role to allow SSM SendCommand action for AWS Lambda service.
Resources:
  LoginPullPushContainers:
    Type: 'AWS::SSM::Document'
    Properties:
      DocumentType: Command
      Content:
        schemaVersion: '2.2'
        description: Pull docker images from IBM Entitlement Registry and upload to ECR
        parameters:
          DockerRegistryEntitlementKey:
            default: !Ref DockerRegistryEntitlementKey
            description: The Production Docker Registry Entitlement Key entered by customer
            type: String
          ECRRegion:
            default: !Ref ECRRegion
            description: Region where ECR is located
            type: String
          ECROrg:
            default: !Ref ECROrg
            description: The AWS organization where ECR is located
            type: String
          FinalLogin:
            default: !Ref FinalLogin
            description: The final login string
            type: String
          CPERepoURI:
            default: !Join
              - ''
              - - !Ref ECROrg
                - '.dkr.ecr.'
                - !Ref ECRRegion
                - '.amazonaws.com/'
                - !Ref CPERepoName
                - ':'
                - !Ref 'CPETag'
            type: String
          ICNRepoURI:
            default: !Join
              - ''
              - - !Ref ECROrg
                - '.dkr.ecr.'
                - !Ref ECRRegion
                - '.amazonaws.com/'
                - !Ref ICNRepoName
                - ':'
                - !Ref 'ICNTag'
            type: String
          CSSRepoURI:
            default: !Join
              - ''
              - - !Ref ECROrg
                - '.dkr.ecr.'
                - !Ref ECRRegion
                - '.amazonaws.com/'
                - !Ref CSSRepoName
                - ':'
                - !Ref 'CSSTag'
            type: String
          CRSRepoURI:
            default: !Join
              - ''
              - - !Ref ECROrg
                - '.dkr.ecr.'
                - !Ref ECRRegion
                - '.amazonaws.com/'
                - !Ref CRSRepoName
                - ':'
                - !Ref 'CRSTag'
            type: String
          CMISRepoURI:
            default: !Join
              - ''
              - - !Ref ECROrg
                - '.dkr.ecr.'
                - !Ref ECRRegion
                - '.amazonaws.com/'
                - !Ref CMISRepoName
                - ':'
                - !Ref 'CMISTag'
            type: String
          CPETag:
            default: !Ref 'CPETag'
            description: The CPE container tag
            type: String
          CSSTag:
            default: !Ref 'CSSTag'
            description: The CSS container tag
            type: String
          CRSTag:
            default: !Ref 'CRSTag'
            description: The GraphQL container tag
            type: String
          ICNTag:
            default: !Ref 'ICNTag'
            description: The ICN container tag
            type: String
          CMISTag:
            default: !Ref 'CMISTag'
            description: The CMIS container tag
            type: String
        mainSteps:
          - action: 'aws:runShellScript'
            name: DockerLoginIBMRegistry
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - '{{FinalLogin}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PullCSSContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'pull cp.icr.io/cp/cp4a/fncm/css:{{CSSTag}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PullCPEContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'pull cp.icr.io/cp/cp4a/fncm/cpe:{{CPETag}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PullICNContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'pull cp.icr.io/cp/cp4a/ban/navigator:{{ICNTag}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PullCMISContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'pull cp.icr.io/cp/cp4a/fncm/cmis:{{CMISTag}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PullCQLContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'pull cp.icr.io/cp/cp4a/fncm/graphql:{{CRSTag}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: TagCSSContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'tag cp.icr.io/cp/cp4a/fncm/css:{{CSSTag}} {{CSSRepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: TagCPEContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'tag cp.icr.io/cp/cp4a/fncm/cpe:{{CPETag}} {{CPERepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: TagICNContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'tag cp.icr.io/cp/cp4a/ban/navigator:{{ICNTag}} {{ICNRepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: TagCMISContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'tag cp.icr.io/cp/cp4a/fncm/cmis:{{CMISTag}} {{CMISRepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: TagCRSContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'tag cp.icr.io/cp/cp4a/fncm/graphql:{{CRSTag}} {{CRSRepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: ExecuteAWSGetECRLogin
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"eval"'
                    - '`aws ecr get-login --region {{ECRRegion}} --no-include-email`'
                    - '> /root/docker_login.out'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PushCPEContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'push {{CPERepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PushCSSContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'push {{CSSRepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PushICNContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'push {{ICNRepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: pushCMISContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'push {{CMISRepoURI}}'
              workingDirectory: '/home/ec2-user'
          - action: 'aws:runShellScript'
            name: PushCRSContainer
            maxAttempts: 3
            onFailure: Abort
            inputs:
              runCommand:
                - !Join
                  - ' '
                  - - '"/usr/bin/docker"'
                    - 'push {{CRSRepoURI}}'
              workingDirectory: '/home/ec2-user'
  dbamcExecuteLoginPullPushContainersDocumentLambda:
    Type: 'AWS::Lambda::Function'
    DependsOn:
      - LoginPullPushContainers
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.7
      Code:
        ZipFile: !Join
          - |+

          - - import boto3
            - 'import os, time,json'
            - import cfnresponse
            - import logging
            - ''
            - 'def lambda_handler(event, context):'
            - '    print(''Received event: %s'' % json.dumps(event))'
            - '    status = cfnresponse.SUCCESS'
            - '    try:'
            - '        if event[''RequestType''] == ''Delete'':'
            - '            cfnresponse.send(event, context, status, {})'
            - '        else:'
            - '            ssm = boto3.client(''ssm'')'
            - ''
            - '            asg = boto3.client(''autoscaling'')'
            - '            asg_name = event[''ResourceProperties''][''BastionASGName'']'
            - '            responseAsg = asg.describe_auto_scaling_groups(AutoScalingGroupNames=[asg_name])'
            - '            instanceId = responseAsg[''AutoScalingGroups''][0][''Instances''][0][''InstanceId'']'
            - '            ssmDocument = event[''ResourceProperties''][''SSMDocument'']'
            - '            responseData = {}'
            - ''
            - '            response=ssm.send_command('
            - '                InstanceIds = [instanceId],'
            - '                DocumentName=ssmDocument,'
            - '                TimeoutSeconds=3600,'
            - '                Comment=''Pulling docker images, tagging images, and pushing to AWS ECR'','
            - '                CloudWatchOutputConfig={''CloudWatchOutputEnabled'': True},'
            - '                MaxConcurrency=''50'','
            - '                MaxErrors=''5'','
            - '            )'
            - ''
            - '            cmdId = response[''Command''][''CommandId'']'
            - '            responseData[''CommandId''] = cmdId'
            - '            print(''Started object creation in CommandId: '' + cmdId)'
            - '            print(''Bastion Host Instance: '' + instanceId)'
            - '            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)'
            - '    except Exception as e:'
            - '        logging.error(''Exception: %s'' % e, exc_info=True)'
            - '        status = cfnresponse.FAILED'
            - '        cfnresponse.send(event, context, status, {}, None)'
      Description: Pulling docker images, tagging images, and pushing to AWS ECR
      MemorySize: 320
      Timeout: 180
      Role: !Ref FNCMSSMSendCommandLambdaRoleARN
  dbamcExecutedbamcConfigObjectsDocument1:
    Type: 'Custom::dbamcExecutedbamcConfigObjectsDocument1'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt
        - dbamcExecuteLoginPullPushContainersDocumentLambda
        - Arn
      SSMDocument: !Ref LoginPullPushContainers
      BastionASGName: !Ref BastionASGName
Outputs:
  CPERepoURI:
    Value: !Join
      - ''
      - - !Ref ECROrg
        - '.dkr.ecr.'
        - !Ref ECRRegion
        - '.amazonaws.com/'
        - !Ref CPERepoName
        - ':'
        - !Ref 'CPETag'
  ICNRepoURI:
    Value: !Join
      - ''
      - - !Ref ECROrg
        - '.dkr.ecr.'
        - !Ref ECRRegion
        - '.amazonaws.com/'
        - !Ref ICNRepoName
        - ':'
        - !Ref 'ICNTag'
  CMISRepoURI:
    Value: !Join
      - ''
      - - !Ref ECROrg
        - '.dkr.ecr.'
        - !Ref ECRRegion
        - '.amazonaws.com/'
        - !Ref CMISRepoName
        - ':'
        - !Ref 'CMISTag'
  CSSRepoURI:
    Value: !Join
      - ''
      - - !Ref ECROrg
        - '.dkr.ecr.'
        - !Ref ECRRegion
        - '.amazonaws.com/'
        - !Ref CSSRepoName
        - ':'
        - !Ref 'CSSTag'
  CRSRepoURI:
    Value: !Join
      - ''
      - - !Ref ECROrg
        - '.dkr.ecr.'
        - !Ref ECRRegion
        - '.amazonaws.com/'
        - !Ref CRSRepoName
        - ':'
        - !Ref 'CRSTag'
